Feature 19
abes-esr/licencesnationales-front pull request #32
Opened 2021-11-16 14:03 UTC by SamuelQuetin

Feature 19 creation compte

2021-11-16 14:15 UTC, fretif commented on src/components/etablissement/Contact.vue
> +          @keyup.enter="validate()"
ajouter
autocomplete="false"

2021-11-16 14:18 UTC, fretif commented on src/components/etablissement/FormEtablissement.vue
> +              <v-btn x-large color="secondary" @click="clear"> Effacer</v-btn>
quand je clique sur effacer puis sur enregistrer, toutes les règles sur les champs ne sont pas vérifiées
![image](https://user-images.githubusercontent.com/7263307/142001982-aaaa6d7a-6116-484d-b967-f1e1aacdba2f.png)

2021-11-16 14:20 UTC, fretif commented on src/components/etablissement/FormEtablissement.vue
> +                v-model="etablissement.typeEtablissement"
les types d'établissement sont vides lorsque l'API n'est pas disponible
![image](https://user-images.githubusercontent.com/7263307/142002357-9fe4e3c6-4845-4c0c-a990-9d102f3b9356.png)

2021-11-16 14:26 UTC, fretif commented on src/components/etablissement/Contact.vue
> +            :rules="rulesForms.passwordRules"
Erreur 'Le mot de passe doit contenir des lettres dont au moins une majuscule, au moins un chiffre et un caractère spécial, et faire 8 caractères minimum'
il faut préciser 'un caractère spécial parmis @ $ ! % * ? &'

Pourquoi ce mot de passe ne fonctionne pas : lklklklklklkl45!!:,;@KK

La règle est peut-être mal exprimée.

2021-11-16 14:32 UTC, fretif commented on src/components/etablissement/Contact.vue
> +            @keyup.enter="validate()"
mot de passe non identique et je n'ai pas d'erreur
![image](https://user-images.githubusercontent.com/7263307/142004502-8b24bcc7-696f-441f-896f-d988b96468d3.png)

2021-11-17 14:32 UTC, SamuelQuetin commented on src/components/etablissement/Contact.vue
> +            :rules="rulesForms.passwordRules"
lklklklklklkl45!!:,;@kk n'a pas de majuscule donc c'est normal et les ";" et "," ne sont pas autorisé

2021-11-17 14:34 UTC, SamuelQuetin commented on src/components/etablissement/FormEtablissement.vue
> +                @click="validate()"
si l'api n'est pas lancer, le formulaire doit faire apparaitre une pop up disant de réessayer plus tard ?

2021-11-17 15:31 UTC, fretif commented on src/components/etablissement/FormEtablissement.vue
> +                @click="validate()"
Problème n°1 : Le formulaire devrait être grisé et il faudrait indiquer de réessayer plus tard
Problème n°2 : a-t-il été traité ?

2021-11-17 15:33 UTC, fretif commented on src/components/etablissement/Contact.vue
> +            :rules="rulesForms.passwordRules"
OK, alors je n'ai pas compris la règle comme quoi tous les autres caractères spéciaux sont interdits sauf @ $ ! % * ? &
Je pense qu'il faut reformuler la phrase.
Est-il possible d'avoir une erreur claire sur la(les) contrainte(s) non respectée(s) ? typiquement ici que je n'ai pas mis de majuscule ?

2021-11-17 15:47 UTC, fretif requested changes

2021-11-17 15:47 UTC, fretif commented on src/components/etablissement/Contact.vue
> +          @keyup.enter="validate()"
Il y a toujours le bug d'autocomplétion (en jaune) par le navigateur de mon mail et mot de passe que j'ai enregistré pour ce site

![image](https://user-images.githubusercontent.com/7263307/142232143-8f25a236-f17b-4ab7-b15f-4f71c91e18cd.png)

2021-11-17 15:47 UTC, fretif commented on src/components/etablissement/Contact.vue
> +          @keyup.enter="validate()"
Si je saisi la confirmation du mail avant le mail :

![image](https://user-images.githubusercontent.com/7263307/142232772-45aafd4a-7fde-4cda-9514-2aa6d38c7508.png)

2021-11-17 15:47 UTC, fretif commented on src/components/etablissement/Contact.vue
> +          @keyup.enter="validate()"
Il y a toujours le bug d'autocomplétion (en jaune) par le navigateur de mon mail et mot de passe que j'ai enregistré pour ce site

2021-11-17 15:47 UTC, fretif commented on src/components/etablissement/Contact.vue
> +            @click:append="show1 = !show1"
Il y a toujours le bug d'autocomplétion (en jaune) par le navigateur de mon mail et mot de passe que j'ai enregistré pour ce site

2021-11-18 08:10 UTC, SamuelQuetin commented on src/components/etablissement/Contact.vue
> +            :rules="rulesForms.passwordRules"
par exemple si tu oublie une majuscule, il affiche un message avec juste "il manque une majuscule" puis une fois la majuscule mis, il check si les autres regles sont respecter et envoyer un message un par un ?

2021-11-18 08:11 UTC, fretif commented on src/components/etablissement/Contact.vue
> +            :rules="rulesForms.passwordRules"
Yes, ça serait top pour les utilisateurs

2021-11-18 08:13 UTC, SamuelQuetin commented on src/components/etablissement/FormEtablissement.vue
> +                @click="validate()"
Probleme n°1 : ok ca sera fait
Probleme n°2 : non pas encore traité

2021-11-18 08:15 UTC, SamuelQuetin commented on src/components/etablissement/Contact.vue
> +          @keyup.enter="validate()"
ok donc ca doit bien etre le probleme que tu avais envoyer : [vuetifyjs/vuetify#2792](https://github.com/vuetifyjs/vuetify/issues/2792)

2021-12-07 15:29 UTC, merged